# Generated by Django 4.2.3 on 2024-02-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moviegenre",
            options={
                "ordering": ["name"],
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.RemoveIndex(
            model_name="movie",
            name="movies_movi_ganre_i_55a537_idx",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="ganre",
        ),
        migrations.RemoveField(
            model_name="moviegenre",
            name="genre",
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(to="movies.moviegenre", verbose_name="Жанры"),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.ImageField(
                blank=True, null=True, upload_to="posters/", verbose_name="Постер"
            ),
        ),
        migrations.AddField(
            model_name="moviegenre",
            name="description",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="moviegenre",
            name="name",
            field=models.CharField(
                default=None, max_length=255, verbose_name="Название жанра"
            ),
            preserve_default=False,
        ),
    ]
