# Generated by Django 4.2.3 on 2024-02-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_alter_director_name_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.CharField(max_length=2000, verbose_name="Текст"),
        ),
    ]
