# Generated by Django 4.2.3 on 2024-02-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_movie_slug_alter_review_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="director",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
