# Generated by Django 4.2.3 on 2024-02-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_director_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviegenre",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="director",
            name="description",
            field=models.TextField(
                blank=True, max_length=300, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="director",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(max_length=300, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="moviegenre",
            name="description",
            field=models.TextField(
                blank=True, max_length=300, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddIndex(
            model_name="director",
            index=models.Index(fields=["name"], name="movies_dire_name_7fd370_idx"),
        ),
        migrations.AddIndex(
            model_name="moviegenre",
            index=models.Index(fields=["name"], name="movies_movi_name_18582a_idx"),
        ),
    ]
