# Generated by Django 4.2.3 on 2024-02-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0007_moviegenre_slug_alter_director_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="director",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название фильма"
            ),
        ),
        migrations.AlterField(
            model_name="moviegenre",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название жанра"
            ),
        ),
    ]
