# Generated by Django 4.2.3 on 2024-03-02 15:35

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0009_alter_movie_title_alter_movie_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True, null=True, upload_to="posters/", verbose_name="Постер"
            ),
        ),
    ]
