# Generated by Django 4.2.3 on 2024-03-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
